# Generated by Django 2.2 on 2020-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('contacting_for', models.CharField(choices=[('Please Choose', 'Please Choose'), ('Training', 'Training'), ('Web Applications', 'Web Applications'), ('Android/IOS Apps', 'Android/IOS Apps')], default='Please Choose', max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquire_Course_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('select_course', models.CharField(choices=[('Python Web Development', 'Python Web Development'), ('Java Web Development', 'Java Web Development'), ('Full Stack Training', 'Full Stack Training'), ('Java & Python', 'Java & Python')], default='Python Web Development', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choice_one', models.CharField(max_length=60)),
                ('choice_two', models.CharField(max_length=60)),
                ('choice_three', models.CharField(max_length=60)),
                ('choice_four', models.CharField(max_length=60)),
                ('answer', models.CharField(max_length=60)),
            ],
        ),
    ]
